### ISSUE TITLE
Add to "Questions people want to ask Translator" based on last round of research

### ISSUE THREAD

**Issue by cmajel** [ncats/nih-ncats-translator#31]
We have asked during our interviews if there are questions participants may want to ask of Translator and tracking them. This is an issue to review our last round of research (round 3) and update the list as needed.

Done when:
- [ ] Interview notes are reviewed
- [ ] [Questions we want Translator to answer](https://docs.google.com/spreadsheets/d/1ZtL3oAixNPCYsB-hzMpGeW6hrLmpCtBTdPekeRP6xDY/edit#gid=0) sheet is updated 
- [ ] Additional issues are created as needed

**Comment by jposi** [comment]
What questions would they want to ask translator? @aditirao to tell @cmajel which interviews to look at.
**limit to an hour of work.**

**Comment by aditirao** [comment]
added link to spreadsheet up above. remaining interviews to check:

- [ ] S2UXR11
- [ ] S3UXR05
- [ ] S3UXR12
- [ ] S3UXR13

**Comment by aditirao** [comment]
@cmajel I reviewed the notes and added the questions. The last thing remaining to do is to put what the input categories are. Can you check w/ Kyle to determine that? (Or maybe you can do it yourself... my brain's just to fried to do it now) Question numbers 22, 27, and 28 in the spreadsheet. Thanks!

**Comment by cmajel** [comment]
@aditirao awesome! I've updated the input categories with the help of @krbrim - closing this!
