### ISSUE TITLE
Document user needs / remaining questions from "Ask a question" usability round

### ISSUE THREAD

**Issue by cmajel** [ncats/nih-ncats-translator#58]
## User Story

As a designer, I want to make sure the enhancements and open questions we identified from prior rounds of testing are documented in git so that future teams have the information and background to investigate further.

## Definition of Done
- [x] Research recap is done
- [x] We decide how these items should be tagged (Questions? Feature request? Assessment needed? Research round 02 - ask a question?)
- [x] Related issues are created and tagged appropriately

**Additional Notes:**

**Comment by cmajel** [comment]
I've reviewed [the research recap from our "How users ask a question" round](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g4eb21fd7af_0_178). Below are the items I've identified to be folded into the backlog as issues.

@jposi and @adunkman, would love feedback on the best way to document these, and if the "Keep doing" issues should be documented as notes for future engineers. Currently, I am thinking of creating seperate issues for each with the labels:
* `Usability finding` 
* `Research Round 2: Usability for query interface`

## Specific to the application

### Keep doing (should these be issues?)

* Provide categories for terms in the dropdown to help with name collision ([Slide 20](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_58))
* Give sources for term and category definitions ([Slide 20](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_58))
* Provide type aheads to help discover matchable terms ([Slide 23](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_79))
* Allow users to easily modify their search on the results page and do new searches. ([Slide 37](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_165))
* Provide and explain outside sources where references ([Slide 48](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_3_69))


### Updates, edits and additions
* Provide a resource explaining how Translator defines and names terms ([Slide 20](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_58))
* Consider other ways to communicate the breadth of data besides placeholder text ([Slide 22](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_73))
* Add definitions immediately after search, rather than as its own step ([Slide 31](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_127))
* Consider alternative language for "explore this term" ([Slide 40](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_3_20))
* Consider alternative names for "synonyms" panel ([Slide 41](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_3_38))
* Revisit how we visualize hierarchies, and the "more specific vs more general" language for hierarchies ([Slide 44](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_3_44))
* Revisit the way users can adjust their search from definition panels ([Slide 44](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_3_44))

## Future features
* Assess the viability and need for searching on "families" of terms. ([Slide 25](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_4_3))
* Show hierarchy for terms when searching and allow searching on a "parent and its children" ([Slide 24](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_85))
* Consider structure previews when searching for chemical compounds ([Slide 26](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_95))
* Consider error handling for searching - spelling errors? "Did you mean"? Suggested searches? (Slide 27)
* Save search history so that users can review past searches and recreate them ([Slide 37](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_165))
* Design a no results page. Distinguish between no results because of no connections vs lack of data. Consider what searches should be suggested instead ([Slide 37](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_165))

## Larger questions
* Phenotype vs disease, what is the best way to proceed and limit name collision? ([Slide 20](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_58))
* What initial content would help users understand what Translator is and what is possible? How should it be explained on the home page? Should we provide sample queries? What should they be? ([Slide 37](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_165))
* How can we identify and combat semantic chasm realities? Are there feedback loops we could implement to identify friction? Or exercises that could be done to get users up to speed quickly on new fields? ([Slide 50](https://docs.google.com/presentation/d/1O1m8rcRL0BANlsTsZu6atkNtxPOmk8HvBWmQf5SS2-0/edit#slide=id.g5c73dbe24b_2_179))

**Comment by aditirao** [comment]
Here is the [Consolidated user research findings](https://drive.google.com/open?id=1L-3Lx7yW8nDBtXNNGEdZmAfFENtC0tciJUfJ4saR5Rg) doc

**Comment by cmajel** [comment]
per convo with @jposi , the "what worked well" could live in a final presentation or in the consolidated research findings, while issues / questions can exist as git issues.

**Comment by jposi** [comment]
worksession with Kyle on Thursday, we'll do what we can without this being too insane.

**Comment by cmajel** [comment]
This is all set with an assist from @krbrim!  🎉 🎉
