### ISSUE TITLE
Only return terms which will produce hive plot results.

### ISSUE THREAD

**Issue by adunkman** [ncats/nih-ncats-translator#68]
Related to the implementation of #6.

## User Story

As a person searching for terms to see the connections between, I want to select the term among synonymous terms that has results so that I see results.

## Definition of Done

- A beginner user can select terms which has the potential for showing results in the hive plot.

**Comment by adunkman** [comment]
I’ve just discovered that the API we’re using is apparently searching PubMed articles as well — because a search for `something` returns a PubMed article, *Canine Cystinuria - Something Old, Something New*.

```json
{
  "id": "PMID:8334504",
  "id_std": "PMID:8334504",
  "id_eng": "PMID:8334504",
  "id_kw": "PMID:8334504",
  "prefix": "PMID",
  "label": [
    "Canine Cystinuria - Something Old, Something New"
  ],
  "label_std": [
    "Canine Cystinuria - Something Old, Something New"
  ],
  "label_eng": [
    "Canine Cystinuria - Something Old, Something New"
  ],
  "label_kw": [
    "Canine Cystinuria - Something Old, Something New"
  ],
  "edges": 2,
  "category": [
    "publication"
  ],
  "category_std": [
    "publication"
  ],
  "category_eng": [
    "publication"
  ],
  "category_kw": [
    "publication"
  ],
  "equivalent_curie": [
    "PubMed:8334504",
    "BNODE:omiaarticlekey39779"
  ],
  "equivalent_curie_std": [
    "PubMed:8334504",
    "BNODE:omiaarticlekey39779"
  ],
  "equivalent_curie_eng": [
    "PubMed:8334504",
    "BNODE:omiaarticlekey39779"
  ],
  "equivalent_curie_kw": [
    "PubMed:8334504",
    "BNODE:omiaarticlekey39779"
  ],
  "leaf": true,
  "_version_": 1643063795692601300,
  "score": 85.10257
}
```

**Comment by MarkDWilliams** [comment]
Yes, I think there are some nodes that are just publications stored in the database.  I don't think these come up often in query results in my experience.  Which API did this come from, the Robokop one?

**Comment by adunkman** [comment]
From [this endpoint](https://api.monarchinitiative.org/api/search/entity/something) — the [BioLink API](https://api.monarchinitiative.org/api/) (but this issue is to re-evaluate that choice).

**Comment by MarkDWilliams** [comment]
Ah, yes.  This may have been from earlier in the project when people were considering having publications represented as objects.  Typically, PMIDs are attached to edges making assertions now.  Is the presence of publication objects causing issues?  It should be possible to filter on the category field if you want to exclude them.
