### ISSUE TITLE
Create a new wireframe for Sept 2019 usability testing

### ISSUE THREAD

**Issue by cmajel** [ncats/nih-ncats-translator#82]
We will be testing a new wireframe concept based on #40. 

## Definition of Done
* [x] Task list is decided #81 
* [x] Wireframe is uploaded to Invision and shared with the team
* [x] Aim to have it set by Weds 8/28
  * [Final wireframe for user interviews](https://gsa.invisionapp.com/share/DQTQS6ZE8TB#/381507105_0-0_-_Welcome)

**Additional Notes:**

**Comment by jposi** [comment]
@cmajel pretty sure this can be closed? or leave it open for your last taskin slack with the strength meter?

**Comment by cmajel** [comment]
@jposi yes! I've updated the issue with the final testing urls.
